ls:
  .js: kebab-case
  .json: kebab-case
  .md: kebab-case
  .yml: kebab-case

  .dir: kebab-case

  tests:
    fake:
      migrations: snake_case

ignore:
  - .git
  - .github
  - node_modules
  - .idea
  - README.md
  - INSTALLER.md
  - CONTRIBUER.md
