# https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs
name: test

on: [push]

env:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-usage-of-the-vars-context
  API_LISTENING_PORT: ${{ vars.API_LISTENING_PORT }}
  RNIPP_BASE_URL: ${{ vars.RNIPP_BASE_URL }}
  RNIPP_TIMEOUT_MILLISECONDS: ${{ vars.RNIPP_TIMEOUT_MILLISECONDS }}
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  # fakes
  FAKE_RNIPP_API_LISTENING_PORT: ${{ vars.FAKE_RNIPP_API_LISTENING_PORT }}
  FAKE_PAJEMPLOI_API_LISTENING_PORT: ${{ vars.FAKE_PAJEMPLOI_API_LISTENING_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments#using-environments-without-deployments
    environment:
      name: main
      deployment: false
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version: '26.8.1'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: start database
        uses: gullerya/db-setup-action@v1.1.0
        with:
          image: 'postgres:17.11-alpine'
          port: 5432
          username: postgres
          # can't pass $DATABASE_USER_PASSWORD environment variable to reusable workflow
          # https://github.com/orgs/community/discussions/26671
          password: password
          database: database
      - name: create database schema
        run: npm run database:migrate
      - name: create fake database schema
        run: npm run fake:database:migrate
      - name: run tests
        run: npm run test
      - name: start API
        run: npm start &
      - name: wait for API to be available
        run: npx wait-on --timeout 2000 http://localhost:$API_LISTENING_PORT/api
      - name: start fake RNIPP
        run: npm run fake:rnipp:start &
      - name: wait for RNIPP to be available
        run: npx wait-on --timeout 2000 $RNIPP_BASE_URL
      - name: run end-to-end tests
        run: npm run test:end-to-end
